services:
    keyrock:
        image: fiware/idm:${KEYROCK_VERSION} #7.8.1
        env_file:
            - ../.env
        container_name: keyrock
        hostname: keyrock
        depends_on:
            - mysql-db
        ports:
            - "${KEYROCK_PORT}:${KEYROCK_PORT}" #3000
            #- "${KEYROCK_HTTPS_PORT}:${KEYROCK_HTTPS_PORT}" #443
        expose:
            - "${KEYROCK_PORT}" #3000
        environment:
            - DEBUG=idm:*
            - IDM_DB_HOST=mysql-db
            - IDM_HOST=http://localhost:${KEYROCK_PORT}
            - IDM_PORT=${KEYROCK_PORT}
            # Development use only
            # Use Docker Secrets for Sensitive Data
            - IDM_DB_PASS=secret
            - IDM_DB_USER=root
            - IDM_ADMIN_USER=admin
            - IDM_ADMIN_EMAIL=admin@test.com
            - IDM_ADMIN_PASS=1234
            - IDM_DB_HOST=mysql-db
            # If sending eMails point to any STMP server
            #- IDM_EMAIL_HOST=mailer
            #- IDM_EMAIL_PORT=25


    mysql-db:
        restart: always
        image: mysql:5.7
        env_file:
            - ../.env
        hostname: mysql-db
        container_name: db-mysql
        ports:
            - '${MYSQL_PORT}:${MYSQL_PORT}'
        expose:
            - '${MYSQL_PORT}'
        environment:
            # Development use only
            # Use Docker Secrets for Sensitive Data
            #- 'MYSQL_ROOT_USER=root'
            - 'MYSQL_ROOT_PASSWORD=secret'
            - 'MYSQL_ROOT_HOST=keyrock'
        volumes:
            - mysql-db:/var/lib/mysql
            - ./mysql-data:/docker-entrypoint-initdb.d



    # If sending eMails point to any STMP server
    # mailer:
    #     restart: always
    #     image: mazdermind/docker-mail-relay
    #     env_file:
    #         - ../.env
    #     hostname: mailer
    #     container_name: keyrock-mailer
    #     ports:
    #         - '25:25'
    #     environment:
    #         - SMTP_LOGIN=<login> # Login to connect to the external relay
    #         - SMTP_PASSWORD=<password> # Password to connect to the external relay
    #         - EXT_RELAY_HOST=<hostname> # External relay DNS name
    #         - EXT_RELAY_PORT=25
    #         - ACCEPTED_NETWORKS=172.18.1.0/24
    #         - USE_TLS=no

volumes:
    mysql-db: ~
    mysql-db-conf: ~


