services:
  orion-proxy:
    image: fiware/pep-proxy
    env_file:
      - ../.env
    hostname: fiware-orion-proxy
    container_name: wilma
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "${WILMA_PORT}:${WILMA_PORT}" # localhost:1027
    expose:
      - "${WILMA_PORT}"
    environment:
      - DEBUG=pep-proxy:*
      - PEP_PROXY_DEBUG=false
      - PEP_PROXY_APP_HOST=scorpio
      - PEP_PROXY_APP_PORT=9090
      - PEP_PROXY_PORT=${WILMA_PORT}
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_AUTH_ENABLED=false
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=${KEYROCK_PORT}
      - PEP_PROXY_APP_ID=30df5445-79a7-4fd0-9513-6c826fcd603a
      - PEP_PROXY_USERNAME=pep_proxy_475ff6dc-8a65-4bc5-ac28-391fe43af3b8
      - PEP_PASSWORD=pep_proxy_8dce1abd-f863-4609-b83e-477618cfbaf2
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_MAGIC_KEY=1234
      - PEP_PROXY_PUBLIC_PATHS=/version
      
