services:
  orion-proxy:
    image: fiware/pep-proxy
    env_file:
      - ../.env
    hostname: fiware-orion-proxy
    container_name: wilma
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "${WILMA_PORT}:${WILMA_PORT}" # localhost:1027
    expose:
      - "${WILMA_PORT}"
    environment:
      - DEBUG=pep-proxy:*
      - PEP_PROXY_DEBUG=true
      - PEP_PROXY_APP_HOST=orion
      - PEP_PROXY_APP_PORT=${ORION_PORT}
      - PEP_PROXY_PORT=${WILMA_PORT}
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_HTTPS_ENABLED=false
      - PEP_PROXY_AUTH_ENABLED=true
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=${KEYROCK_PORT}
      - PEP_PROXY_APP_ID=b6486dea-9157-4edb-94f9-e17eeb64597f
      - PEP_PROXY_USERNAME=pep_proxy_f05e351d-fee6-4c4f-9256-9c1d34745ac1
      - PEP_PASSWORD=pep_proxy_ba31bfe2-d147-4c06-b6c2-20a5eda5b924
      - PEP_PROXY_PDP=idm
      - PEP_PROXY_MAGIC_KEY=1234
      - PEP_PROXY_PUBLIC_PATHS=/version
      
