version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181"

  ld-context:
    image: httpd:alpine
    hostname: context
    container_name: fiware-ld-context
    ports:
      - "3004:80"
    volumes:
      - ../data-models:/usr/local/apache2/htdocs/
      - type: bind
        source: ../conf/mime.types
        target: /usr/local/apache2/conf/mime.types
        read_only: true
    healthcheck:
      test: (wget --server-response --spider --quiet  http://context/user-context.jsonld 2>&1 | awk 'NR==1{print $$2}'|  grep -q -e "200") || exit 1

  kafka:
    image: bitnami/kafka:3.5.1-debian-11-r6
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper


  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wirepass
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  scorpio:
    image: scorpiobroker/all-in-one-runner:java-kafka-latest
    hostname: scorpio
    ports:
      - "9090:9090"
    environment:
      DBHOST: postgres
      BUSHOST: kafka
      DBUSER: postgres
      DBPASS: wirepass
      DBNAME: postgres
    depends_on:
      - postgres
      - kafka